[tool.poetry]
name = "mlops-cmc-2023"
version = "0.0.1"
description = "simple knn"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.0"
pandas = "^1.3.2"
sklearn = "^0.0"

[tool.poetry.group.dev.dependencies]
python = "^3.10"
numpy = "^1.26.0"
pandas = "^1.3.2"
sklearn = "^0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
