name: "base_model"
backend: "pytorch"
max_batch_size: 64
input [
    {
        name: "input__0"
        data_type: TYPE_FP64
        dims: [785]
    }
]
output [
    {
        name: "output__0"
        data_type: TYPE_FP64
        dims: [10]
    }
]

dynamic_batching: {max_queue_delay_microseconds: 5}
